"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

>>> 4613732
"""
import timeit


def solution1(MAX_SIZE):
    
    def fib(a, b):
        if not a & 1:
            yield a
        while b < MAX_SIZE:
            if not b & 1:
                yield b
            a, b, = b, a + b

    return sum(fib(1, 2))

print(solution1(4000000))
print(timeit.timeit("solution1(MAX_SIZE=4000000)", setup="from __main__ import solution1", number=10000))

